# Generated by Django 4.0.4 on 2023-04-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0005_alter_curso_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='comision',
            field=models.CharField(max_length=23),
        ),
    ]
