# Generated by Django 4.0.4 on 2023-04-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0005_alter_curso_comision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='apellitod',
            new_name='apellido',
        ),
    ]
