# Generated by Django 4.0.4 on 2023-04-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0006_rename_apellitod_profesor_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellitod',
            new_name='apellido',
        ),
    ]
